### ISSUE TITLE
Can you provide a non-italic comments skew on each color scheme?

### ISSUE THREAD

**Issue by endigma** [radiolevity/search-lights#10]
I don't know if themes are able to have settings, a setting would be nice if possible.

**Comment by finnjames** [comment]
I'm following the general trend of always rendering comments as italics, but of course if it's an issue for you, just add the following to your `settings.json`:

```json
"editor.tokenColorCustomizations": {
  "[Search Lights]": {
    "textMateRules": [
      {
        "scope": [
          "comment",
          "punctuation.definition.comment",
        ],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  },
  "[Desert Lights]": {
    "textMateRules": [
      {
        "scope": [
          "comment",
          "punctuation.definition.comment",
        ],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  }
},
```
I have considered transitioning from having italics versions to having non-italics versions. I have only delayed this so far to avoid inconvenience to the "set it and forget it" users. It's on my long-term task list.
