### ISSUE TITLE
Italicized variant?

### ISSUE THREAD

**Issue by teenwolfblitzer** [radiolevity/search-lights#3]
Love this theme, it's become my favorite for daily use!

I'm using [Jetbrains Mono](https://www.jetbrains.com/lp/mono/) as my default font, and some themes I've used in the past (like [Night Owl](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl)) have additional support for italic text, which helps to visually call out functions, etc when scanning code. I'm wondering if there are plans to enable this behavior.

**Comment by finnjames** [comment]
I added a first draft on an italic variant in 1.10.0—please let me know if there are any issues with it
