### ISSUE TITLE
Desert Lights: Bold or Italic (or Bold Italic!) 

### ISSUE THREAD

**Issue by carlomunguia** [radiolevity/search-lights#4]
Greetings! Love to jam with Desert Lights usually as my daily driving coding theme. 
Any plans for a Bold, Italic or Bold Italic variant specifically for the Desert Lights variant?

The dark, dusty yet vibrant & colorful desert vibe is wonderful!  A dash of bold or italic on modifiers or inheritance would take it to the next level (at least in my view)

**Comment by finnjames** [comment]
I'm happy with how the Search Lights italic variant came out, so I'll add a Desert Lights version as well. I will consider a bold (and bold italic) for a future release.

**Comment by finnjames** [comment]
Added as of 1.10.1. If you find any errors, don't hesitate to open an issue.
