### ISSUE TITLE
JSX tags aren't visually appealing

### ISSUE THREAD

**Issue by endigma** [radiolevity/search-lights#7]
![image](https://user-images.githubusercontent.com/34945114/147610156-546c9c34-ee77-462c-9801-84021eac48da.png)
(jsx)

vs 

![image](https://user-images.githubusercontent.com/34945114/147610184-c0b7af7b-9937-4db2-b0ed-08a1747d09ee.png)
(html)

html way is much prettier, should be propagated to JSX/anything else that uses white for whatever reason

**Comment by endigma** [comment]
Seems to actually be a svelte issue

**Comment by endigma** [comment]
fixed this in a fork, has to do with default `entity.name.tag` coloring, merge that fix into upstream if you want

https://github.com/endigma/search-lights

**Comment by finnjames** [comment]
Thanks for the fix! I can't pull the changes since you also modified the package file and readme. Can you open a new branch with just the json file changes? Otherwise, I'll just copy and paste the changes into the repo, but then you won't get contributor credit here on GH.

**Comment by endigma** [comment]
#8
